import type {Metadata} from "next";
import {Roboto} from 'next/font/google'
import "./globals.css";
import {UiProviders} from "./providers/ui-providers";
import {ThemeProvider as NextThemesProvider} from "next-themes";
import Header from "@/components/header";
import Footer from "@/components/footer";
import LayoutSpacer from "@/components/wrapper/LayoutSpacer";

const roboto = Roboto({
    weight: ['100', '300', '400', '500', '700', '900'],
    subsets: ["latin"]
});

export const metadata: Metadata = {
    title: "Flash card",
    description: "Generated by create next app",
};
export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={roboto.className}>
        <UiProviders>
            <NextThemesProvider attribute="class" defaultTheme="dark">
                <Header/>
                <LayoutSpacer>
                    {children}
                    <Footer/>
                </LayoutSpacer>
            </NextThemesProvider>
        </UiProviders>
        </body>
        </html>
    );
}
